config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'admin_orders/index'
    get 'admin_orders/show'
  end
  devise_for :customer_tables, controllers: {
      registrations: 'publilc/registrations',
      sessions: 'public/sessions'
  }

  devise_for :admins, controllers: {
  #   homes: "admin/homes",
      registrations: 'admin/registrations',
      sessions: 'admin/sessions'
  #   menues: "admin/menues",
  #   genres: "admin/genres",
  #   users: "admin/users",
  #   orders: "admin/orders",
  #   order_details: "admin/order_details"
  }

#mydomain.com/menues
  scope module: :public do
     get 'about' => 'homes#about', as: 'about'
    resources :menus, only:[:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy_cart_items'
    resources :cart_items, only:[:new, :index, :create, :update, :destroy]
    resources :comments,  only:[:new, :create, :destroy]
    get 'orders/confirm' => 'orders#confirm', as: 'confirm_orders'
    get 'orders/complete' => 'orders#complete', as: 'complete_orders'
    resources :orders, only:[:new, :create, :index, :show]
    resources :customer_tables, only:[:new, :show]
    #tablesがながのケーキでいうcustomerテーブル。
  end

  get "admin" => "homes#top"
  namespace :admin do
    resources :menus, only:[:new, :index, :create, :show, :edit, :update, :destroy]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :users, only:[:new, :index, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :admin_orders, only:[:index, :show, :update]
    resources :admin_order_details, only:[:update]
    resources :customer_tables, only:[:index, :edit, :update, :new, :create]
  end

  devise_scope :customer_table do
    root to: 'public/sessions#new'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/admin_order.rb
class AdminOrder < ApplicationRecord
  has_many :admin_order_details
  belongs_to :customer_table
end

app/models/admin_order_detail.rb
class AdminOrderDetail < ApplicationRecord

  belongs_to :admin_order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.admin_order.admin_order_details
    if self.making_status == "調理中"
      self.admin_order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.admin_order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.admin_order.update(status: 0)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer_table
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer_table.rb
class CustomerTable < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable


  has_many :cart_items
  has_many :orders
  has_many :admin_orders

  validates :email, uniqueness: true
  validates :customer_tables_name, uniqueness: true

  def has_in_cart(menu)
    cart_items.find_by(menu_id: menu.id)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :menus

end

app/models/menu.rb
class Menu < ApplicationRecord

  #self.table_name = "menus"

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_many :admin_order_details
  has_many :tags, dependent: :destroy

  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :customer_table


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.order.order_details
    if self.making_status == "調理中"
      self.order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.order.update(status: 0)
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :menu
end

app/controllers/admin/admin_orders_controller.rb
class Admin::AdminOrdersController < ApplicationController

  def index
    if params[:customer_tables_name]
      @customer_table = CustomerTable.find(params[:customer_tables_name])
      @orders = @customer_table.orders.page(params[:page]).reverse_order
    elsif params[:created_at] == "today"
      @admin_orders = AdminOrder.ordered_today.includes(:customer_table).page(params[:page]).reverse_order
    else
      @admin_orders = AdminOrder.includes(:customer_table).page(params[:page]).reverse_order
    end
  end

  def show
    @order = AdminOrder.find(params[:id])
    @order_details = @order.admin_order_details
    @customer_table = @order.customer_table
  end

  def update
    if @order.update(order_params) && @order.confirm_deposit?
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def ensure_order
    @order = Order.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:customer_tables_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:customer_tables_name])
  end

  def after_sign_in_path_for(resource)
    menus_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/helpers/admin/admin_orders_helper.rb
module Admin::AdminOrdersHelper
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_message(status)
    if status == "未着手"
      ""
    else
      status
    end
  end
end

app/views/admin/admin_orders/index.html.erb
<div class="container">
 <div class="row">
	<h2 class="section-ttl">
		<% if params[:customer_id] %>
			<%= @customer.full_name %>さんの注文履歴一覧
		<% elsif params[:created_at] == "today" %>
			本日の注文履歴一覧
		<% else %>
			注文履歴一覧
		<% end %>
	</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>注文日</th>
				<th>購入者</th>
				<th>注文個数</th>
				<th>総計</th>
				<th>注文ステータス</th>
			</tr>
		</thead>
		<tbody>
			<% @admin_orders.each do |admin_order| %>
				<tr>
					<td><%= link_to admin_order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_admin_order_path(admin_order), class: "underline" %></td>
					<td><%= link_to admin_order.customer_table.customer_tables_name, admin_admin_order_path(admin_order.id) %></td>
					<td><%= admin_order.admin_order_details.sum(:amount) %></td>
					<td><%= admin_order.total_payment %>円</td>
					<td><% if admin_order.status == 0 %>
					<p>未着手</p>
					<% elsif admin_order.status == 1 %>
					<p>調理中</p>
					<% elsif admin_order.status == 2 %>
					<p>提供済<p>
					<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= paginate @admin_orders %>
 </div>
</div>

app/views/admin/admin_orders/show.html.erb
<div style="margin-left: 60px;">
	<section class="inner">
	<h2 class="section-ttl">注文履歴詳細</h2>
		<table class="order_info mb3 has_border">
			<caption class="fz18 text-left">注文情報</caption>
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>注文日時</td>
					<td><%= @order.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
				</tr>
				<tr>
					<td>購入者</td>
					<td><%= @customer_table.customer_tables_name %></td>
				</tr>
				<tr>
					<td>注文ステータス</td>
					<td>
						<%= @check_status %>
						<% if @order.status == 0 %>
						<p style="margin: 0 !important;">未着手</p>
						<% elsif @order.status == 1 %>
						<p>調理中</p>
						<% elsif @order.status == 2 %>
						<p>提供済<p>
						<% end %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="flex">
			<table class="table table-borderd border-dark">
				<thead>
					<tr>
						<th scope="col">商品名</th>
						<th scope="col">金額</th>
						<th scope="col">数量</th>
						<th scope="col">小計</th>
						<th scope="col">ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @order_details.each do |admin_order_detail| %>
						<% menu = admin_order_detail.menu %>
						<tr>
							<% if menu.nil? %>
								<td scope="row">該当する商品がありません。</td>
							<% else %>
								<td><%= menu.menu_name %></td>
							<% end %>
								<td><%= admin_order_detail.price %>円</td>
								<td><%= admin_order_detail.amount %></td>
								<td><%= admin_order_detail.price * admin_order_detail.amount %>円</td>
								<td><%= form_with model: admin_order_detail, url: admin_admin_order_detail_path(admin_order_detail), method: :patch, local: true do |f| %>
									<%= f.select :making_status, AdminOrderDetail.making_statuses.keys, class: 'form-control ml-3' %>
									<%= f.submit "更新", class: "btn btn-primary" %>
									<% end %>
								</td>
						</tr>
					<% end %>
				</tbody>
			</table>



			<!--<table class="admin_order_details mr2 has_border">-->
			<!--	<caption class="fz18 text-left">注文内容</caption>-->
			<!--	<thead>-->
			<!--		<tr>-->
			<!--			<th>商品名</th>-->
			<!--			<th>単価</th>-->
			<!--			<th>数量</th>-->
			<!--			<th>小計</th>-->
			<!--			<th>ステータス</th>-->
			<!--		</tr>-->
			<!--	</thead>-->

			<div class="row">
				<table class="table table-bordered border-dark col-4">
					<thead>
						<tr>
							<th style="border-color: black;">商品合計</th>
							<th style="border-color: black;"><%= @order.total_payment %>円</th>
						</tr>
					</thead>
					<tbody>
						<tr>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</section>
</div>