config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'admin_orders/index'
    get 'admin_orders/show'
  end
  devise_for :customer_tables, controllers: {
      registrations: 'publilc/registrations',
      sessions: 'public/sessions'
  }

  devise_for :admins, controllers: {
  #   homes: "admin/homes",
      registrations: 'admin/registrations',
      sessions: 'admin/sessions'
  #   menues: "admin/menues",
  #   genres: "admin/genres",
  #   users: "admin/users",
  #   orders: "admin/orders",
  #   order_details: "admin/order_details"
  }

#mydomain.com/menues
  scope module: :public do
     get 'about' => 'homes#about', as: 'about'
    resources :menus, only:[:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy_cart_items'
    resources :cart_items, only:[:new, :index, :create, :update, :destroy]
    resources :comments,  only:[:new, :create, :destroy]
    get 'orders/confirm' => 'orders#confirm', as: 'confirm_orders'
    get 'orders/complete' => 'orders#complete', as: 'complete_orders'
    resources :orders, only:[:new, :create, :index, :show]
    resources :customer_tables, only:[:new, :show]
    #tablesがながのケーキでいうcustomerテーブル。
  end

  get "admin" => "homes#top"
  namespace :admin do
    resources :menus, only:[:new, :index, :create, :show, :edit, :update, :destroy]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :users, only:[:new, :index, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :admin_orders, only:[:index, :show, :update]
    resources :admin_order_details, only:[:update]
    resources :customer_tables, only:[:index, :edit, :update, :new, :create]
  end

  devise_scope :customer_table do
    root to: 'public/sessions#new'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/admin_order.rb
class AdminOrder < ApplicationRecord
  has_many :admin_order_details
  belongs_to :customer_table
end

app/models/admin_order_detail.rb
class AdminOrderDetail < ApplicationRecord

  belongs_to :admin_order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.admin_order.admin_order_details
    if self.making_status == "調理中"
      self.admin_order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.admin_order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.admin_order.update(status: 0)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer_table
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer_table.rb
class CustomerTable < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable


  has_many :cart_items
  has_many :orders
  has_many :admin_orders

  validates :email, uniqueness: true
  validates :customer_tables_name, uniqueness: true

  def has_in_cart(menu)
    cart_items.find_by(menu_id: menu.id)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :menus

end

app/models/menu.rb
class Menu < ApplicationRecord

  #self.table_name = "menus"

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_many :admin_order_details
  has_many :tags, dependent: :destroy

  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :customer_table


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.order.order_details
    if self.making_status == "調理中"
      self.order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.order.update(status: 0)
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :menu
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page])
  end

  def new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def show
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      unless @genre.is_active
        @genre.menus.update_all(is_active: false)
      end
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

   private

  def genre_params
    params.require(:genre).permit(:genres_name, :is_active)
  end

  def ensure_genre
    @genre = Genre.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:customer_tables_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:customer_tables_name])
  end

  def after_sign_in_path_for(resource)
    menus_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/helpers/admin/admin_orders_helper.rb
module Admin::AdminOrdersHelper
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_message(status)
    if status == "未着手"
      ""
    else
      status
    end
  end
end

app/views/admin/genres/_form.html.erb
<%= form_with model:genre, url: url, local: true do |f| %>
	<%#= render 'layouts/error_messages', resource: genre %>
	<%= f.label :gemres_name, "ジャンル名:" %>
	<%= f.text_field :genres_name, style: "margin-right: 10px;" %>
	<%= f.radio_button :is_active, true %>
	<%= f.label :is_active, "有効", class: "text-active", style: "margin-right: 10px;" %>
	<%= f.radio_button :is_active, false %>
	<%= f.label :is_active, "無効", class: "text-invalid", style: "margin-right: 10px;" %>
	<%= f.submit submit, class: "btn btn-primary ml2" %>
<% end %>

app/views/admin/genres/edit.html.erb
<div class="container">
	<h2 class="section-ttl">ジャンル編集画面</h2>
  	<div class="form-group">
      <%= render 'form', genre: @genre, url: admin_genre_path(@genre), submit: '更新' %>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container", style="margin-left: 300px;">
	<h2>ジャンル管理</h2>
		<table class='table table-bordered'>
				<h4>ジャンル新規登録</h4>
		  	 <%= render 'form', genre: @genre, url: admin_genres_path, submit: '登録' %>
		</table>

	<div class="row">
		<div class="col-md-4">
			<h3>ジャンル一覧</h3>
			<table class="table">
				<thead>
					<tr>
						<th>ジャンル名</th>
						<th>状態</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @genres.each do |genre| %>
						<tr>
							<td><%= link_to genre.genres_name, admin_menus_path(genre_id: genre.id), class: "underline" %></td>
							<td>
								<% if genre.is_active? %>
									<span class="text-active">有効</span>
								<% else %>
									<span class="text-invalid">無効</span>
								<% end %>
							</td>
							<td class="text-center"><%= link_to "編集", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<%= paginate @genres %>
</div>