config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'admin_orders/index'
    get 'admin_orders/show'
  end
  devise_for :customer_tables, controllers: {
      registrations: 'publilc/registrations',
      sessions: 'public/sessions'
  }

  devise_for :admins, controllers: {
  #   homes: "admin/homes",
      registrations: 'admin/registrations',
      sessions: 'admin/sessions'
  #   menues: "admin/menues",
  #   genres: "admin/genres",
  #   users: "admin/users",
  #   orders: "admin/orders",
  #   order_details: "admin/order_details"
  }

#mydomain.com/menues
  scope module: :public do
     get 'about' => 'homes#about', as: 'about'
    resources :menus, only:[:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy_cart_items'
    resources :cart_items, only:[:new, :index, :create, :update, :destroy]
    resources :comments,  only:[:new, :create, :destroy]
    get 'orders/confirm' => 'orders#confirm', as: 'confirm_orders'
    get 'orders/complete' => 'orders#complete', as: 'complete_orders'
    resources :orders, only:[:new, :create, :index, :show]
    resources :customer_tables, only:[:new, :show]
    #tablesがながのケーキでいうcustomerテーブル。
  end

  get "admin" => "homes#top"
  namespace :admin do
    resources :menus, only:[:new, :index, :create, :show, :edit, :update, :destroy]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :users, only:[:new, :index, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :admin_orders, only:[:index, :show, :update]
    resources :admin_order_details, only:[:update]
    resources :customer_tables, only:[:index, :edit, :update, :new, :create]
  end

  devise_scope :customer_table do
    root to: 'public/sessions#new'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/admin_order.rb
class AdminOrder < ApplicationRecord
  has_many :admin_order_details
  belongs_to :customer_table
end

app/models/admin_order_detail.rb
class AdminOrderDetail < ApplicationRecord

  belongs_to :admin_order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.admin_order.admin_order_details
    if self.making_status == "調理中"
      self.admin_order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.admin_order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.admin_order.update(status: 0)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer_table
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer_table.rb
class CustomerTable < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable


  has_many :cart_items
  has_many :orders
  has_many :admin_orders

  validates :email, uniqueness: true
  validates :customer_tables_name, uniqueness: true

  def has_in_cart(menu)
    cart_items.find_by(menu_id: menu.id)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :menus

end

app/models/menu.rb
class Menu < ApplicationRecord

  #self.table_name = "menus"

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_many :admin_order_details
  has_many :tags, dependent: :destroy

  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :customer_table


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.order.order_details
    if self.making_status == "調理中"
      self.order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.order.update(status: 0)
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :menu
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController

  before_action :authenticate_admin!
  before_action :ensure_menu, only: [:show, :edit, :update, :destroy]

  def new
    @menu = Menu.new
  end

  def index
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      all_menus = @genre.menus
    else
      all_menus = Menu.includes(:genre)
    end
    @menus = all_menus.page(params[:page])
    @all_menus_count = all_menus.count
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save! ? (redirect_to admin_menus_path(@menu)) : (render :new)
    if @menu.image.present?
      tags = Vision.get_image_data(@menu.image)
      tags.each do |tag|
        @menu.tags.create(name: tag)
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    @menu.update(menu_params) ? (redirect_to admin_menu_path(@menu)) : (render :edit)
  end

  def destroy
   @menu.destroy
   redirect_to admin_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:genre_id, :menu_name, :introduction, :image, :price, :is_active)
  end

  def ensure_menu
    @menu = Menu.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:customer_tables_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:customer_tables_name])
  end

  def after_sign_in_path_for(resource)
    menus_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/helpers/admin/admin_orders_helper.rb
module Admin::AdminOrdersHelper
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_message(status)
    if status == "未着手"
      ""
    else
      status
    end
  end
end

app/views/admin/menus/_form.html.erb
	<%#= render 'layouts/error_messages', resource: menu %>
<div class='container'>
	<div class='row justify-content-center'>
	  <%= form_with model:menu, url: url do |f| %>
			<div>
				<%= f.label :image, "画像" %>
				<div class="row image_field">
					<div class="col-4">
					 <%= image_tag (menu.image.attached? ? menu.image : 'no_image.jpg'), id: "img_prev", class: "admin_menu_image" %>
					</div>
					<div class="col-4">
					 <span class="btn btn-file btn-info"><%= f.file_field :image,  accept:'image/*' %>画像選択</span>
					</div>
				</div>
				<p>選択するとプレビューされます。<br>画像未選択のままだと、<br>「画像準備中」になります。</p>
			</div>
			<table class="admin_item_info item_form">
				<thead>
					<tr>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= f.label :menu_name, "商品名" %></td>
						<td><%= f.text_field :menu_name %></td>
					</tr>
					<tr>
						<td><%= f.label :introduction, "商品説明" %></td>
						<td><%= f.text_area :introduction, rows: 5, cols: 50, class: "mt-3 mb-3" %></td>
					</tr>
					<tr>
						<td><%= f.label :genre_id, "ジャンル" %></td>
						<td class="select_field"><div class="mb-3"><%= f.collection_select :genre_id, Genre.all, :id, :genres_name %></div></td>
					</tr>
					<tr>
						<td><%= f.label :price, "価格" %></td>
						<td><%= f.number_field :price, class: "mb-3" %> 円</td>
					</tr>
					<tr>
						<td><%= f.label :sales_status, "販売ステータス", class: "mb-3" %></td>
						<td class="select_field">
							<div class="mb-3">
								<%= f.radio_button :is_active, true %>
								<%= f.label :is_active, "販売中", class: "text-active m-0"  %>
								<%= f.radio_button :is_active, false %>
								<%= f.label :is_active, "販売停止中", class: "text-invalid m-0" %>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="text-center">
				<%= f.submit submit, class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/menus/_index.html.erb
<div class='container'>
	<table class="table table-hover">
		<div class="text-left">
			<%= link_to "+", new_admin_menu_path, class: "new_admin_menu h4" %>
			<% if menus.any? %>
				<%= link_to "商品登録", new_admin_menu_path, class: "underline h4" %>
			<% end %>
		</divv>
		<thead>
			<tr>
				<th>商品ID</th>
				<th>商品名</th>
				<th>価格</th>
				<th>ジャンル</th>
				<th>販売ステータス</th>
			</tr>
		</thead>
		<tbody>
			<% menus.each do |menu| %>
				<tr>
					<td class="text-center"><%= menu.id %></td>
					<td><%= link_to menu.menu_name, admin_menu_path(menu.id), class: "underline" %></td>
					<td class="text-center"><%= menu.price %>円</td>
					<td><% if menu.genre != nil %><%= link_to menu.genre.genres_name, admin_menus_path(genre_id: menu.genre_id) %><% end %></td>
					<td>
						<% if menu.is_active? %>
							<span class="text-active">販売中</span>
						<% else %>
							<span class="text-invalid">販売停止中</span>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/menus/edit.html.erb
<section class="inner">
	<h2 class="section-ttl"><%= @menu.menu_name %>の編集</h2>
  <%= render 'form', menu: @menu, url: admin_menu_path(@menu), submit: '更新' %>
</section>

app/views/admin/menus/index.html.erb
<div class='container'>
	<div class="inner">
		<% if params[:genre_id] %>
			<h2 class="section-ttl"><%= @genre.genres_name %>の商品一覧 (全<%= @all_menus_count %>件)</h2>
		<% else %>
			<h2 class="section-ttl">商品一覧 (全<%= @all_menus_count %>件)</h2>
		<% end %>
		<%= render 'admin/menus/index', menus: @menus %>
		<%= paginate @menus %>
	</div>
</div>

app/views/admin/menus/new.html.erb
<section class="inner">
<div class='container'>
	<div class='row'>
     <h2 class="section-ttl">商品新規登録</h2>
  </div>
</div>
  <%= render 'form', menu: @menu, url: admin_menus_path, submit: '登録' %>
</section>

app/views/admin/menus/show.html.erb
<div class='container'>
	<h2>商品詳細</h2>
		<div class='row'>

			<div class="col-xl-5 text-center">
					<%= image_tag (@menu.image.attached? ? @menu.image : 'no_image.jpg'), id: "img_prev", class: "admin_menu_image" %>
					<div class="mt-3 tag-box">
						<% @menu.tags.each do |tag| %>
					  <span class="label"><%= tag.name %></span>
						<% end %>
					</div>
			</div>



        <div class="col-xl-7">
        	<div align="center">
	          <table>
								<tr>
									<th><h4>商品名</h4></th>
									<th><%= @menu.menu_name %></th>
								</tr>
								<tr>
									<th><h4>商品説明</h4></th>
									<th><%= @menu.introduction %></th>
								</tr>
								<tr>
									<th><h4>ジャンル</h4></th>
									<th><%= link_to @menu.genre.genres_name, admin_genres_path, class: "underline" %></th>
								</tr>
								<tr>
									<th><h4>税抜価格</h4></th>
									<th><%= @menu.price %>円</th>
								</tr>
								<tr>
									<th><h4>販売ステータス</h4></th>
									<th>
										<% if @menu.is_active? %>
											<span class="text-active">販売中</span>
										<% else %>
											<span class="text-invalid">販売停止中</span>
										<% end %>
									</th>
								</tr>
						</table><br>
							<div class="flex align-center pl5">
					     <%= link_to "編集する", edit_admin_menu_path(@menu), class: "btn btn-success" %>
					      <%= link_to "削除する", admin_menu_path(@menu), method: :delete, data: {confirm: "#{@menu.menu_name}を削除します。よろしいでしょうか？"}, class: "btn btn-success" %>
			      	</div>
					</div>
        </div>

		</div>
</div>