config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'admin_orders/index'
    get 'admin_orders/show'
  end
  devise_for :customer_tables, controllers: {
      registrations: 'publilc/registrations',
      sessions: 'public/sessions'
  }

  devise_for :admins, controllers: {
  #   homes: "admin/homes",
      registrations: 'admin/registrations',
      sessions: 'admin/sessions'
  #   menues: "admin/menues",
  #   genres: "admin/genres",
  #   users: "admin/users",
  #   orders: "admin/orders",
  #   order_details: "admin/order_details"
  }

#mydomain.com/menues
  scope module: :public do
     get 'about' => 'homes#about', as: 'about'
    resources :menus, only:[:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: 'all_destroy_cart_items'
    resources :cart_items, only:[:new, :index, :create, :update, :destroy]
    resources :comments,  only:[:new, :create, :destroy]
    get 'orders/confirm' => 'orders#confirm', as: 'confirm_orders'
    get 'orders/complete' => 'orders#complete', as: 'complete_orders'
    resources :orders, only:[:new, :create, :index, :show]
    resources :customer_tables, only:[:new, :show]
    #tablesがながのケーキでいうcustomerテーブル。
  end

  get "admin" => "homes#top"
  namespace :admin do
    resources :menus, only:[:new, :index, :create, :show, :edit, :update, :destroy]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :users, only:[:new, :index, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :admin_orders, only:[:index, :show, :update]
    resources :admin_order_details, only:[:update]
    resources :customer_tables, only:[:index, :edit, :update, :new, :create]
  end

  devise_scope :customer_table do
    root to: 'public/sessions#new'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/admin_order.rb
class AdminOrder < ApplicationRecord
  has_many :admin_order_details
  belongs_to :customer_table
end

app/models/admin_order_detail.rb
class AdminOrderDetail < ApplicationRecord

  belongs_to :admin_order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.admin_order.admin_order_details
    if self.making_status == "調理中"
      self.admin_order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.admin_order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.admin_order.update(status: 0)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer_table
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer_table.rb
class CustomerTable < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable


  has_many :cart_items
  has_many :orders
  has_many :admin_orders

  validates :email, uniqueness: true
  validates :customer_tables_name, uniqueness: true

  def has_in_cart(menu)
    cart_items.find_by(menu_id: menu.id)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :menus

end

app/models/menu.rb
class Menu < ApplicationRecord

  #self.table_name = "menus"

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_many :admin_order_details
  has_many :tags, dependent: :destroy

  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :customer_table


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :menu

  enum making_status: {未着手:0, 調理中:1, 提供済:2}
    #注文ステータスの変更
  def change_making_status
    menu = self.order.order_details
    if self.making_status == "調理中"
      self.order.update(status: 1)
    elsif menu.pluck(:making_status).all?{ |status| status == "提供済"}
      self.order.update(status: 2)
    elsif menu.pluck(:making_status).all?{ |status| status == "未着手"}
      self.order.update(status: 0)
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :menu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:customer_tables_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:customer_tables_name])
  end

  def after_sign_in_path_for(resource)
    menus_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_message(status)
    if status == "未着手"
      ""
    else
      status
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MechaChumonEasyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

<body style="background-color: #FFFFCC">
    <header class="border-bottom" style="height: 100px; background-color: #33FF66">
      <ul class="nav justify-content-around" style="padding-top: 30px;">
        <li class="nav-item">
          <i class="fas fa-utensils"></i>
          <%= link_to 'MechaChumonEasy', (admin_signed_in? ? admin_menus_path : root_path ), class: "logo" %>
        </li>

        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to '商品一覧',  admin_menus_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to '未会計のオーダー',  admin_orders_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
             <%= link_to '注文履歴一覧',  admin_admin_orders_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ジャンル一覧',  admin_genres_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'テーブル番号一覧',   admin_customer_tables_path, class: "nav-link active" %>
          </li>
          <li class="nav-item mr-5">
            <%= button_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link active" %>
          </li>
        <% elsif customer_table_signed_in? %>
          <div class="text-center">
            <p>ようこそ、<%= current_customer_table.customer_tables_name %>さん!</p>
          </div>
          <li class="nav-item row">
            <%= link_to '商品一覧', menus_path, class: "nav-link active btn btn--orange"  %>
            <%= link_to 'カート', cart_items_path, class: "nav-link active btn btn--orange" %>
            <%= link_to '注文履歴一覧', orders_path, class: "nav-link active btn btn--orange" %>
            <%= button_to 'お会計', destroy_customer_table_session_path, method: :delete, class: "nav-link active btn btn--orange" %>
          </li>
        <% end %>
      </ul>
    </header>

    <!--    </ul>-->
        <%# if admin_signed_in? %>
          <%#= form_tag(admin_search_path, method: :get) do %>
            <%#= text_field_tag "search[content]", "", :placeholder =>"会員: 姓,名,セイ,メイ / 商品: 商品名" %>
            <%#= select_tag "search[model]", options_for_select({ "会員" => "customer", "商品" => "item" }) %>
            <%#= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
            <%#= submit_tag '検索', class: "btn btn-primary" %>
          <%# end %>
        <%# end %>
        <!--検索機能。時間があったら実装する。-->

      </div>
    </header>
    <main class = "mt-5">
      <%= yield %>
    </main>

  </body>
</html>